local controllers = script.Parent:WaitForChild("Controllers")

local FirstPersonController = require(controllers:WaitForChild("FirstPersonController"))
local AimController = require(controllers:WaitForChild("AimController"))
local StageClientController = require(controllers:WaitForChild("StageClientController"))
local RewardClientController = require(controllers:WaitForChild("RewardClientController"))
local InputHintController = require(controllers:WaitForChild("InputHintController"))
local SprintController = require(controllers:WaitForChild("SprintController"))
local CrouchController = require(controllers:WaitForChild("CrouchController"))
local MusicController = require(controllers:WaitForChild("MusicController"))

FirstPersonController.Init()
AimController.Init()
MusicController.Init()
InputHintController.Init()
SprintController.Init()
CrouchController.Init()
StageClientController.Init()
RewardClientController.Init()
